# 20 Questions from Numpy Exercises (Without Answers)

## 1. 
Create a null vector of size 10 with a `float32` data type.

---

## 2. 
How to find the indices of non-zero elements in an array?

---

## 3. 
Create a 3x3 matrix with values ranging from 1 to 9.

---

## 4. 
Create a 1D array of 10 random values and reshape it to a 3x3x3 array.

---

## 5. 
How can you compare two arrays to check if they are equal?

---

## 6. 
Create an array of 10 random values and find the maximum value.

---

## 7. 
Create a 5x5 2D array with 1 on the border and 0 inside.

---

## 8. 
How can you reverse an array?

---

## 9. 
Create a 5x5 matrix with random values and find the minimum and maximum values.

---

## 10. 
How to create a 1D array with values ranging from 0 to 9?

---

## 11. 
How to create a diagonal matrix using a 1D array?

---

## 12. 
Create a 4x4 matrix and extract the sub-matrix consisting of the 2nd and 3rd rows and columns.

---

## 13. 
How to normalize an array to the range [0, 1]?

---

## 14. 
Create a random vector of size 30 and find the mean value.

---

## 15. 
How to add a border of zeros around an existing array?

---

## 16. 
Create a 3x3 identity matrix.

---

## 17. 
How to generate a random number between 0 and 1?

---

## 18. 
How to replace all elements greater than a given value in an array with that value?

---

## 19. 
Create a random 5x5 matrix and compute the row-wise mean.

---

## 20. 
How to swap two rows in a matrix?


In [2]:
import numpy as np

In [3]:
#1.
none = np.empty([2, 5], dtype='float32')
print(none.size)
print(none)

10
[[2.2828399e-32 0.0000000e+00 0.0000000e+00 0.0000000e+00 6.0747855e-32]
 [0.0000000e+00 4.1015725e-32 0.0000000e+00 6.7262326e-44 0.0000000e+00]]


In [6]:
#2.
arr2 = np.array([[1, 0, 3, 0, 9], [2, 2, 2, 0, 2], [4, 0, 2, 0, 2]])
non_zero = np.nonzero(arr2)
print(arr2)
print(non_zero)

[[1 0 3 0 9]
 [2 2 2 0 2]
 [4 0 2 0 2]]
(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2]), array([0, 2, 4, 0, 1, 2, 4, 0, 2, 4]))


In [11]:
#3.
arr3 = np.arange(1, 10)
re_arr3 = arr3.reshape(3, 3)
print(arr3)
print(re_arr3)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
#4.
arr4 = np.random.rand(27)
print(arr4)
re_arr4 = arr4.reshape(3, 3, 3)
print(re_arr4)

[0.8904793  0.51562463 0.80958414 0.87346395 0.57118216 0.43401179
 0.39334003 0.04700537 0.56739364 0.54994204 0.71814822 0.93422017
 0.06445675 0.8706047  0.08938242 0.18182281 0.2613723  0.872933
 0.87597979 0.2615059  0.34775625 0.40037866 0.29546729 0.0260408
 0.66973865 0.90997629 0.62622437]
[[[0.8904793  0.51562463 0.80958414]
  [0.87346395 0.57118216 0.43401179]
  [0.39334003 0.04700537 0.56739364]]

 [[0.54994204 0.71814822 0.93422017]
  [0.06445675 0.8706047  0.08938242]
  [0.18182281 0.2613723  0.872933  ]]

 [[0.87597979 0.2615059  0.34775625]
  [0.40037866 0.29546729 0.0260408 ]
  [0.66973865 0.90997629 0.62622437]]]


In [15]:
#5.
arr5_1 = np.array([1, 1, 2])
arr5_2 = np.array([1, 1, 2])
arr5_3 = np.array([1, 2, 2])
print(np.array_equal(arr5_1, arr5_2))
print(np.array_equal(arr5_1, arr5_3))

True
False


In [22]:
#6.
arr6 = np.random.rand(10)
print(arr6)
print(np.max(arr6))

[0.01235494 0.85599256 0.88839297 0.29507529 0.89806435 0.56857159
 0.93696747 0.2996738  0.90214666 0.56258154]
0.9369674680569845


In [28]:
#7
arr7 = np.zeros((5, 5))
arr7[[0, 4]] = 1
#arr7[:, [0, 4]] = 1
print(arr7)

[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]


In [33]:
#8
arr8 = np.array(([1, 2, 3], [4, 5, 6]))
arr8_1 = np.flip(arr8)
print(arr8_1)


[[6 5 4]
 [3 2 1]]


In [44]:
#9
arr9 = np.random.rand(5, 5)
print(arr9)
max_index = np.unravel_index(np.argmax(arr9), arr9.shape)
min_index = np.unravel_index(np.argmin(arr9), arr9.shape)
arr9_max = arr9.max()
max_index = tuple(map(int, max_index))
min_index = tuple(map(int, min_index))
print('max --> ',arr9_max, 'at', max_index)
arr9_min = arr9.min()
print('min --> ',arr9_min, 'at', min_index)

[[0.97136821 0.37406573 0.41837225 0.37685826 0.9395849 ]
 [0.30435413 0.40389365 0.68736848 0.76609024 0.37587923]
 [0.11282851 0.87027147 0.31148404 0.21595671 0.24091073]
 [0.92167308 0.82287684 0.14575891 0.35854047 0.36961867]
 [0.66276753 0.83676004 0.30028197 0.44478708 0.9891703 ]]
max -->  0.9891703021962394 at (4, 4)
min -->  0.11282850841885306 at (2, 0)


In [45]:
#10
arr10 = np.arange(0, 9)
print(arr10)

[0 1 2 3 4 5 6 7 8]


In [49]:
#11
arr11 = np.array([1, 2, 3])
arr11_diag = np.diag(arr11)
arr11_diag_1 = np.diag(arr11, k=1)
print(arr11_diag)
print(arr11_diag_1)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]


In [51]:
#12
arr12 = np.arange(1, 17).reshape(4, 4)
print(arr12)
arr12_sub = arr12[1:3, 1:3]
print(arr12_sub)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 6  7]
 [10 11]]


In [54]:
#13
arr13 = np.array([2, 4, 4, 7, 2, 98, 6])
arr13_min = arr13.min()
arr13_max = arr13.max()
arr13_normalized = (arr13 - arr13_min)/(arr13_max - arr13_min)
print(arr13_normalized)
arr13_normalized_sort = np.sort(arr13_normalized)
print(arr13_normalized_sort)

[0.         0.02083333 0.02083333 0.05208333 0.         1.
 0.04166667]
[0.         0.         0.02083333 0.02083333 0.04166667 0.05208333
 1.        ]


In [58]:
#14
arr14 = np.random.rand(14)
print(arr14)
arr14_mean = np.mean(arr14)
print(arr14_mean)

[0.93338595 0.38670716 0.65095067 0.1761042  0.09384637 0.16526225
 0.28996173 0.75850157 0.39819035 0.44306842 0.20696216 0.34230534
 0.00193839 0.32088318]
0.36914769496355326


In [60]:
#15
arr15 = np.array([1, 2, 3])
arr15_zb = np.pad(arr15, pad_width=1, mode='constant', constant_values=0)
print(arr15_zb)

[0 1 2 3 0]


In [63]:
#16
arr16 = np.identity(3)
print(arr16)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
