In [2]:
import numpy as np

In [46]:
my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list)
print(arr)

[1 2 3 4 5]


In [47]:
matrix = np.array([[1, 2, 3], [5, 6, 7]])
print(matrix)

[[1 2 3]
 [5 6 7]]


In [48]:
zeros = np.zeros((3, 3))
ones = np.ones((6, 4))

print(zeros)
print('--------------------------')
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
--------------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [49]:
random_arr = np.random.rand(3, 3)
print(random_arr)

[[0.118192   0.94214024 0.01238869]
 [0.4626075  0.3502659  0.225487  ]
 [0.7935091  0.53022447 0.13330902]]


In [50]:
arr_2 = np.array([1, 2, 3, 4])
sh_arr = arr_2.reshape(2 ,2)
print(sh_arr)

[[1 2]
 [3 4]]


In [4]:
d = np.arange(0, 50, 5)
print(d)
resh = d.reshape(5, 2)
print(resh)

[ 0  5 10 15 20 25 30 35 40 45]
[[ 0  5]
 [10 15]
 [20 25]
 [30 35]
 [40 45]]


In [8]:
adf = np.array([[2, 3, 4],[6, 34, 6]])
awf = np.array([2, 5, 6])
print(adf.ndim)
print(awf.ndim)
print(adf.shape)
print(awf.shape)

2
1
(2, 3)
(3,)


In [13]:
adfs = np.array([[2, 3, 4],[6, 34, 6]])
awfs = np.array([2, 5, 6])
aa = adfs.dtype
bb = awfs.dtype
print(f'{aa}------{bb}')

int64------int64


In [21]:
adfp = np.array([[2, 3, 4],[6, 34, 6]], dtype='int32')
awfp = np.array([2, 5, 6], dtype='int16')
print(f'{adfp}------------{awfp}')

[[ 2  3  4]
 [ 6 34  6]]------------[2 5 6]


In [22]:
#get.size
ss = awfp.itemsize
print(ss)
#get.total.size
sss = awfp.size * awfp.itemsize
print(sss)

8
24


In [23]:
#get.total.size
dd = awfp.nbytes
print(dd)

24
