In [1]:
import numpy as np

In [9]:
my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list)
print(arr)

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
matrix = np.array([[1, 2, 3], [5, 6, 7]])
print(matrix)

[[1 2 3]
 [5 6 7]]


In [13]:
zeros = np.zeros((3, 3))
ones = np.ones((6, 4))

print(zeros)
print('--------------------------')
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
--------------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [37]:
random_arr = np.random.rand(3, 3)
print(random_arr)

[[0.46993981 0.34295416 0.91949815]
 [0.60577045 0.37299036 0.80800395]
 [0.84342214 0.42942365 0.48652179]]
